apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  minReplicas: {{ .Values.spec.minReplicas }}
  maxReplicas: {{ .Values.spec.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.resource.name }}
      target:
        type: {{ .Values.resource.target.type }}
        averageUtilization: {{ .Values.resource.target.averageUtilization }}